
rm ./Cheat-Sheets-master/html/advanced-ssh-cheat-sheet.html
rm ./Cheat-Sheets-master/html/advanced-ssh-cheat-sheet.md
rm ./Cheat-Sheets-master/html/ansible-cheat-sheet.html
rm ./Cheat-Sheets-master/html/ansible-cheat-sheet.md
rm ./Cheat-Sheets-master/html/ansible-k8s-cheat-sheet.html
rm ./Cheat-Sheets-master/html/ansible-k8s-cheat-sheet.md
rm ./Cheat-Sheets-master/html/bash-cheat-sheet.html
rm ./Cheat-Sheets-master/html/bash-cheat-sheet.md
rm ./Cheat-Sheets-master/html/blender-hotkey-cheat-sheet.html
rm ./Cheat-Sheets-master/html/blender-hotkey-cheat-sheet.md
rm ./Cheat-Sheets-master/html/c-programming-cheat-sheet.html
rm ./Cheat-Sheets-master/html/c-programming-cheat-sheet.md
rm ./Cheat-Sheets-master/html/cheat-sheet-awk-features.html
rm ./Cheat-Sheets-master/html/cheat-sheet-awk-features.md
rm ./Cheat-Sheets-master/html/cheat-sheet-git.html
rm ./Cheat-Sheets-master/html/cheat-sheet-git.md
rm ./Cheat-Sheets-master/html/cheat-sheet-gnome-3.html
rm ./Cheat-Sheets-master/html/cheat-sheet-gnome-3.md
rm ./Cheat-Sheets-master/html/cheat-sheet-i3-window-manager-keybinding.html
rm ./Cheat-Sheets-master/html/cheat-sheet-i3-window-manager-keybinding.md
rm ./Cheat-Sheets-master/html/cheat-sheet-markdown.html
rm ./Cheat-Sheets-master/html/cheat-sheet-markdown.md
rm ./Cheat-Sheets-master/html/cheat-sheet-networking.html
rm ./Cheat-Sheets-master/html/cheat-sheet-networking.md
rm ./Cheat-Sheets-master/html/cheat-sheet-python-37-beginners.html
rm ./Cheat-Sheets-master/html/cheat-sheet-python-37-beginners.md
rm ./Cheat-Sheets-master/html/cheat-sheet-selinux.html
rm ./Cheat-Sheets-master/html/cheat-sheet-selinux.md
rm ./Cheat-Sheets-master/html/cheat-sheet-vim.html
rm ./Cheat-Sheets-master/html/cheat-sheet-vim.md
rm ./Cheat-Sheets-master/html/cheat-sheets.html
rm ./Cheat-Sheets-master/html/cheat-sheets.md
rm ./Cheat-Sheets-master/html/curl-command-cheat-sheet.html
rm ./Cheat-Sheets-master/html/curl-command-cheat-sheet.md
rm ./Cheat-Sheets-master/html/emacs-cheat-sheet.html
rm ./Cheat-Sheets-master/html/emacs-cheat-sheet.md
rm ./Cheat-Sheets-master/html/firewall-cheat-sheet.html
rm ./Cheat-Sheets-master/html/freedos-commands-cheat-sheet.html
rm ./Cheat-Sheets-master/html/getting-started-raspberry-pi-cheat-sheet.html
rm ./Cheat-Sheets-master/html/gnu-debugger-cheat-sheet.html
rm ./Cheat-Sheets-master/html/go-cheat-sheet.html
rm ./Cheat-Sheets-master/html/groff-macros-cheat-sheet.html
rm ./Cheat-Sheets-master/html/inkscape-cheat-sheet.html
rm ./Cheat-Sheets-master/html/java-cheat-sheet.html
rm ./Cheat-Sheets-master/html/jinja2-cheat-sheet.html
rm ./Cheat-Sheets-master/html/jupyterlab-cheat-sheet.html
rm ./Cheat-Sheets-master/html/kubectl-cheat-sheet.html
rm ./Cheat-Sheets-master/html/Kubernetes_A_cheat_sheet.html
rm ./Cheat-Sheets-master/html/Kubernetes_A_cheat_sheet.md.html
rm ./Cheat-Sheets-master/html/linux-common-commands-cheat-sheet.html
rm ./Cheat-Sheets-master/html/linux-permissions-cheat-sheet.html
rm ./Cheat-Sheets-master/html/lua-cheat-sheet.html
rm ./Cheat-Sheets-master/html/mariadb-mysql-cheat-sheet.html
rm ./Cheat-Sheets-master/html/microservices-cheat-sheet.html
rm ./Cheat-Sheets-master/html/open-source-software-alternatives-cheat-sheet.html
rm ./Cheat-Sheets-master/html/pandoc-cheat-sheet.html
rm ./Cheat-Sheets-master/html/pip-cheat-sheet.html
rm ./Cheat-Sheets-master/html/sqlite-cheat-sheet.html
rm ./Cheat-Sheets-master/html/tmux-cheat-sheet.html
rm ./Cheat-Sheets-master/html/Ubuntu_Server_A_cheat_sheet.html
rm ./Cheat-Sheets-master/html/Ubuntu_Server_A_cheat_sheet.md.html
rm ./Cheat-Sheets-master/Markdown/ssh/README.md
